### ISSUE TITLE
Initial development

### ISSUE THREAD

**Issue by rajkumaar23** [rajkumaar23/fcm-manager#1]
- Its a single page application
- Have a login screen.
- For logging in, I'll enter a password which you've to hash & validate against an `env` variable.
- If its valid, store in session(for a month) that user has logged in.
- If logged in, display a form with two fields title, body and a submit button, which should validate the input fields and it should trigger FCM service with the given data.

**Comment by sanjana2610** [comment]
I'll complete the requirements.

**Comment by rajkumaar23** [comment]
Fixed in #3
